#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSellPhone
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webSellPhone")]
	public partial class SQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_banner(tb_banner instance);
    partial void Updatetb_banner(tb_banner instance);
    partial void Deletetb_banner(tb_banner instance);
    partial void Inserttb_danh_muc_phu_kien(tb_danh_muc_phu_kien instance);
    partial void Updatetb_danh_muc_phu_kien(tb_danh_muc_phu_kien instance);
    partial void Deletetb_danh_muc_phu_kien(tb_danh_muc_phu_kien instance);
    partial void InserttbPhuKien(tbPhuKien instance);
    partial void UpdatetbPhuKien(tbPhuKien instance);
    partial void DeletetbPhuKien(tbPhuKien instance);
    partial void Inserttb_danh_muc(tb_danh_muc instance);
    partial void Updatetb_danh_muc(tb_danh_muc instance);
    partial void Deletetb_danh_muc(tb_danh_muc instance);
    partial void Inserttb_sp(tb_sp instance);
    partial void Updatetb_sp(tb_sp instance);
    partial void Deletetb_sp(tb_sp instance);
    partial void Inserttb_don_dat_hang(tb_don_dat_hang instance);
    partial void Updatetb_don_dat_hang(tb_don_dat_hang instance);
    partial void Deletetb_don_dat_hang(tb_don_dat_hang instance);
    #endregion
		
		public SQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_banner> tb_banners
		{
			get
			{
				return this.GetTable<tb_banner>();
			}
		}
		
		public System.Data.Linq.Table<tb_danh_muc_phu_kien> tb_danh_muc_phu_kiens
		{
			get
			{
				return this.GetTable<tb_danh_muc_phu_kien>();
			}
		}
		
		public System.Data.Linq.Table<tbPhuKien> tbPhuKiens
		{
			get
			{
				return this.GetTable<tbPhuKien>();
			}
		}
		
		public System.Data.Linq.Table<tb_danh_muc> tb_danh_mucs
		{
			get
			{
				return this.GetTable<tb_danh_muc>();
			}
		}
		
		public System.Data.Linq.Table<tb_sp> tb_sps
		{
			get
			{
				return this.GetTable<tb_sp>();
			}
		}
		
		public System.Data.Linq.Table<tb_don_dat_hang> tb_don_dat_hangs
		{
			get
			{
				return this.GetTable<tb_don_dat_hang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_banner")]
	public partial class tb_banner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_banner;
		
		private string _ten_banner;
		
		private System.Nullable<int> _hienthi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_bannerChanging(long value);
    partial void Onid_bannerChanged();
    partial void Onten_bannerChanging(string value);
    partial void Onten_bannerChanged();
    partial void OnhienthiChanging(System.Nullable<int> value);
    partial void OnhienthiChanged();
    #endregion
		
		public tb_banner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_banner", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_banner
		{
			get
			{
				return this._id_banner;
			}
			set
			{
				if ((this._id_banner != value))
				{
					this.Onid_bannerChanging(value);
					this.SendPropertyChanging();
					this._id_banner = value;
					this.SendPropertyChanged("id_banner");
					this.Onid_bannerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_banner", DbType="NChar(60)")]
		public string ten_banner
		{
			get
			{
				return this._ten_banner;
			}
			set
			{
				if ((this._ten_banner != value))
				{
					this.Onten_bannerChanging(value);
					this.SendPropertyChanging();
					this._ten_banner = value;
					this.SendPropertyChanged("ten_banner");
					this.Onten_bannerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienthi", DbType="Int")]
		public System.Nullable<int> hienthi
		{
			get
			{
				return this._hienthi;
			}
			set
			{
				if ((this._hienthi != value))
				{
					this.OnhienthiChanging(value);
					this.SendPropertyChanging();
					this._hienthi = value;
					this.SendPropertyChanged("hienthi");
					this.OnhienthiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_danh_muc_phu_kien")]
	public partial class tb_danh_muc_phu_kien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_danh_muc_phu_kien;
		
		private string _ten_danh_muc_phu_kien;
		
		private System.Nullable<int> _hienThi;
		
		private EntitySet<tbPhuKien> _tbPhuKiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danh_muc_phu_kienChanging(long value);
    partial void Onid_danh_muc_phu_kienChanged();
    partial void Onten_danh_muc_phu_kienChanging(string value);
    partial void Onten_danh_muc_phu_kienChanged();
    partial void OnhienThiChanging(System.Nullable<int> value);
    partial void OnhienThiChanged();
    #endregion
		
		public tb_danh_muc_phu_kien()
		{
			this._tbPhuKiens = new EntitySet<tbPhuKien>(new Action<tbPhuKien>(this.attach_tbPhuKiens), new Action<tbPhuKien>(this.detach_tbPhuKiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danh_muc_phu_kien", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_danh_muc_phu_kien
		{
			get
			{
				return this._id_danh_muc_phu_kien;
			}
			set
			{
				if ((this._id_danh_muc_phu_kien != value))
				{
					this.Onid_danh_muc_phu_kienChanging(value);
					this.SendPropertyChanging();
					this._id_danh_muc_phu_kien = value;
					this.SendPropertyChanged("id_danh_muc_phu_kien");
					this.Onid_danh_muc_phu_kienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danh_muc_phu_kien", DbType="NVarChar(50)")]
		public string ten_danh_muc_phu_kien
		{
			get
			{
				return this._ten_danh_muc_phu_kien;
			}
			set
			{
				if ((this._ten_danh_muc_phu_kien != value))
				{
					this.Onten_danh_muc_phu_kienChanging(value);
					this.SendPropertyChanging();
					this._ten_danh_muc_phu_kien = value;
					this.SendPropertyChanged("ten_danh_muc_phu_kien");
					this.Onten_danh_muc_phu_kienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienThi", DbType="Int")]
		public System.Nullable<int> hienThi
		{
			get
			{
				return this._hienThi;
			}
			set
			{
				if ((this._hienThi != value))
				{
					this.OnhienThiChanging(value);
					this.SendPropertyChanging();
					this._hienThi = value;
					this.SendPropertyChanged("hienThi");
					this.OnhienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_danh_muc_phu_kien_tbPhuKien", Storage="_tbPhuKiens", ThisKey="id_danh_muc_phu_kien", OtherKey="id_danh_muc_phu_kien")]
		public EntitySet<tbPhuKien> tbPhuKiens
		{
			get
			{
				return this._tbPhuKiens;
			}
			set
			{
				this._tbPhuKiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPhuKiens(tbPhuKien entity)
		{
			this.SendPropertyChanging();
			entity.tb_danh_muc_phu_kien = this;
		}
		
		private void detach_tbPhuKiens(tbPhuKien entity)
		{
			this.SendPropertyChanging();
			entity.tb_danh_muc_phu_kien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPhuKien")]
	public partial class tbPhuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_phukien;
		
		private string _ten_phu_kien;
		
		private System.Nullable<int> _gia_sp;
		
		private System.Nullable<int> _gia_km;
		
		private string _dung_luong;
		
		private string _cong_sac;
		
		private string _bao_hanh;
		
		private System.Nullable<long> _id_danh_muc_phu_kien;
		
		private string _anh_pk;
		
		private System.Nullable<int> _hienThi;
		
		private EntityRef<tb_danh_muc_phu_kien> _tb_danh_muc_phu_kien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phukienChanging(long value);
    partial void Onid_phukienChanged();
    partial void Onten_phu_kienChanging(string value);
    partial void Onten_phu_kienChanged();
    partial void Ongia_spChanging(System.Nullable<int> value);
    partial void Ongia_spChanged();
    partial void Ongia_kmChanging(System.Nullable<int> value);
    partial void Ongia_kmChanged();
    partial void Ondung_luongChanging(string value);
    partial void Ondung_luongChanged();
    partial void Oncong_sacChanging(string value);
    partial void Oncong_sacChanged();
    partial void Onbao_hanhChanging(string value);
    partial void Onbao_hanhChanged();
    partial void Onid_danh_muc_phu_kienChanging(System.Nullable<long> value);
    partial void Onid_danh_muc_phu_kienChanged();
    partial void Onanh_pkChanging(string value);
    partial void Onanh_pkChanged();
    partial void OnhienThiChanging(System.Nullable<int> value);
    partial void OnhienThiChanged();
    #endregion
		
		public tbPhuKien()
		{
			this._tb_danh_muc_phu_kien = default(EntityRef<tb_danh_muc_phu_kien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phukien", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_phukien
		{
			get
			{
				return this._id_phukien;
			}
			set
			{
				if ((this._id_phukien != value))
				{
					this.Onid_phukienChanging(value);
					this.SendPropertyChanging();
					this._id_phukien = value;
					this.SendPropertyChanged("id_phukien");
					this.Onid_phukienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_phu_kien", DbType="NVarChar(255)")]
		public string ten_phu_kien
		{
			get
			{
				return this._ten_phu_kien;
			}
			set
			{
				if ((this._ten_phu_kien != value))
				{
					this.Onten_phu_kienChanging(value);
					this.SendPropertyChanging();
					this._ten_phu_kien = value;
					this.SendPropertyChanged("ten_phu_kien");
					this.Onten_phu_kienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_sp", DbType="Int")]
		public System.Nullable<int> gia_sp
		{
			get
			{
				return this._gia_sp;
			}
			set
			{
				if ((this._gia_sp != value))
				{
					this.Ongia_spChanging(value);
					this.SendPropertyChanging();
					this._gia_sp = value;
					this.SendPropertyChanged("gia_sp");
					this.Ongia_spChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_km", DbType="Int")]
		public System.Nullable<int> gia_km
		{
			get
			{
				return this._gia_km;
			}
			set
			{
				if ((this._gia_km != value))
				{
					this.Ongia_kmChanging(value);
					this.SendPropertyChanging();
					this._gia_km = value;
					this.SendPropertyChanged("gia_km");
					this.Ongia_kmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dung_luong", DbType="NVarChar(50)")]
		public string dung_luong
		{
			get
			{
				return this._dung_luong;
			}
			set
			{
				if ((this._dung_luong != value))
				{
					this.Ondung_luongChanging(value);
					this.SendPropertyChanging();
					this._dung_luong = value;
					this.SendPropertyChanged("dung_luong");
					this.Ondung_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_sac", DbType="NChar(10)")]
		public string cong_sac
		{
			get
			{
				return this._cong_sac;
			}
			set
			{
				if ((this._cong_sac != value))
				{
					this.Oncong_sacChanging(value);
					this.SendPropertyChanging();
					this._cong_sac = value;
					this.SendPropertyChanged("cong_sac");
					this.Oncong_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bao_hanh", DbType="NVarChar(50)")]
		public string bao_hanh
		{
			get
			{
				return this._bao_hanh;
			}
			set
			{
				if ((this._bao_hanh != value))
				{
					this.Onbao_hanhChanging(value);
					this.SendPropertyChanging();
					this._bao_hanh = value;
					this.SendPropertyChanged("bao_hanh");
					this.Onbao_hanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danh_muc_phu_kien", DbType="BigInt")]
		public System.Nullable<long> id_danh_muc_phu_kien
		{
			get
			{
				return this._id_danh_muc_phu_kien;
			}
			set
			{
				if ((this._id_danh_muc_phu_kien != value))
				{
					if (this._tb_danh_muc_phu_kien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_danh_muc_phu_kienChanging(value);
					this.SendPropertyChanging();
					this._id_danh_muc_phu_kien = value;
					this.SendPropertyChanged("id_danh_muc_phu_kien");
					this.Onid_danh_muc_phu_kienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh_pk", DbType="NVarChar(50)")]
		public string anh_pk
		{
			get
			{
				return this._anh_pk;
			}
			set
			{
				if ((this._anh_pk != value))
				{
					this.Onanh_pkChanging(value);
					this.SendPropertyChanging();
					this._anh_pk = value;
					this.SendPropertyChanged("anh_pk");
					this.Onanh_pkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienThi", DbType="Int")]
		public System.Nullable<int> hienThi
		{
			get
			{
				return this._hienThi;
			}
			set
			{
				if ((this._hienThi != value))
				{
					this.OnhienThiChanging(value);
					this.SendPropertyChanging();
					this._hienThi = value;
					this.SendPropertyChanged("hienThi");
					this.OnhienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_danh_muc_phu_kien_tbPhuKien", Storage="_tb_danh_muc_phu_kien", ThisKey="id_danh_muc_phu_kien", OtherKey="id_danh_muc_phu_kien", IsForeignKey=true)]
		public tb_danh_muc_phu_kien tb_danh_muc_phu_kien
		{
			get
			{
				return this._tb_danh_muc_phu_kien.Entity;
			}
			set
			{
				tb_danh_muc_phu_kien previousValue = this._tb_danh_muc_phu_kien.Entity;
				if (((previousValue != value) 
							|| (this._tb_danh_muc_phu_kien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_danh_muc_phu_kien.Entity = null;
						previousValue.tbPhuKiens.Remove(this);
					}
					this._tb_danh_muc_phu_kien.Entity = value;
					if ((value != null))
					{
						value.tbPhuKiens.Add(this);
						this._id_danh_muc_phu_kien = value.id_danh_muc_phu_kien;
					}
					else
					{
						this._id_danh_muc_phu_kien = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_danh_muc_phu_kien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_danh_muc")]
	public partial class tb_danh_muc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_danh_muc;
		
		private string _ten_danh_muc;
		
		private System.Nullable<int> _hienThi;
		
		private EntitySet<tb_sp> _tb_sps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danh_mucChanging(long value);
    partial void Onid_danh_mucChanged();
    partial void Onten_danh_mucChanging(string value);
    partial void Onten_danh_mucChanged();
    partial void OnhienThiChanging(System.Nullable<int> value);
    partial void OnhienThiChanged();
    #endregion
		
		public tb_danh_muc()
		{
			this._tb_sps = new EntitySet<tb_sp>(new Action<tb_sp>(this.attach_tb_sps), new Action<tb_sp>(this.detach_tb_sps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danh_muc", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_danh_muc
		{
			get
			{
				return this._id_danh_muc;
			}
			set
			{
				if ((this._id_danh_muc != value))
				{
					this.Onid_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._id_danh_muc = value;
					this.SendPropertyChanged("id_danh_muc");
					this.Onid_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danh_muc", DbType="NVarChar(50)")]
		public string ten_danh_muc
		{
			get
			{
				return this._ten_danh_muc;
			}
			set
			{
				if ((this._ten_danh_muc != value))
				{
					this.Onten_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._ten_danh_muc = value;
					this.SendPropertyChanged("ten_danh_muc");
					this.Onten_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienThi", DbType="Int")]
		public System.Nullable<int> hienThi
		{
			get
			{
				return this._hienThi;
			}
			set
			{
				if ((this._hienThi != value))
				{
					this.OnhienThiChanging(value);
					this.SendPropertyChanging();
					this._hienThi = value;
					this.SendPropertyChanged("hienThi");
					this.OnhienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_danh_muc_tb_sp", Storage="_tb_sps", ThisKey="id_danh_muc", OtherKey="id_danh_muc")]
		public EntitySet<tb_sp> tb_sps
		{
			get
			{
				return this._tb_sps;
			}
			set
			{
				this._tb_sps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_sps(tb_sp entity)
		{
			this.SendPropertyChanging();
			entity.tb_danh_muc = this;
		}
		
		private void detach_tb_sps(tb_sp entity)
		{
			this.SendPropertyChanging();
			entity.tb_danh_muc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_sp")]
	public partial class tb_sp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_sanpham;
		
		private string _ten_sanPham;
		
		private System.Nullable<int> _giaSP;
		
		private System.Nullable<int> _giaKM;
		
		private System.Nullable<int> _ton_kho;
		
		private string _man_hinh;
		
		private string _kich_thuoc;
		
		private string _camera;
		
		private string _cong_sac;
		
		private string _anh_sp;
		
		private System.Nullable<int> _sp_hot;
		
		private string _trong_luong;
		
		private string _mau_sac;
		
		private string _bao_hanh;
		
		private string _mo_ta;
		
		private string _xuat_xu;
		
		private System.Nullable<long> _id_danh_muc;
		
		private System.Nullable<int> _hienThi;
		
		private string _pin;
		
		private EntityRef<tb_danh_muc> _tb_danh_muc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sanphamChanging(long value);
    partial void Onid_sanphamChanged();
    partial void Onten_sanPhamChanging(string value);
    partial void Onten_sanPhamChanged();
    partial void OngiaSPChanging(System.Nullable<int> value);
    partial void OngiaSPChanged();
    partial void OngiaKMChanging(System.Nullable<int> value);
    partial void OngiaKMChanged();
    partial void Onton_khoChanging(System.Nullable<int> value);
    partial void Onton_khoChanged();
    partial void Onman_hinhChanging(string value);
    partial void Onman_hinhChanged();
    partial void Onkich_thuocChanging(string value);
    partial void Onkich_thuocChanged();
    partial void OncameraChanging(string value);
    partial void OncameraChanged();
    partial void Oncong_sacChanging(string value);
    partial void Oncong_sacChanged();
    partial void Onanh_spChanging(string value);
    partial void Onanh_spChanged();
    partial void Onsp_hotChanging(System.Nullable<int> value);
    partial void Onsp_hotChanged();
    partial void Ontrong_luongChanging(string value);
    partial void Ontrong_luongChanged();
    partial void Onmau_sacChanging(string value);
    partial void Onmau_sacChanged();
    partial void Onbao_hanhChanging(string value);
    partial void Onbao_hanhChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onxuat_xuChanging(string value);
    partial void Onxuat_xuChanged();
    partial void Onid_danh_mucChanging(System.Nullable<long> value);
    partial void Onid_danh_mucChanged();
    partial void OnhienThiChanging(System.Nullable<int> value);
    partial void OnhienThiChanged();
    partial void OnpinChanging(string value);
    partial void OnpinChanged();
    #endregion
		
		public tb_sp()
		{
			this._tb_danh_muc = default(EntityRef<tb_danh_muc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sanPham", DbType="NVarChar(MAX)")]
		public string ten_sanPham
		{
			get
			{
				return this._ten_sanPham;
			}
			set
			{
				if ((this._ten_sanPham != value))
				{
					this.Onten_sanPhamChanging(value);
					this.SendPropertyChanging();
					this._ten_sanPham = value;
					this.SendPropertyChanged("ten_sanPham");
					this.Onten_sanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaSP", DbType="Int")]
		public System.Nullable<int> giaSP
		{
			get
			{
				return this._giaSP;
			}
			set
			{
				if ((this._giaSP != value))
				{
					this.OngiaSPChanging(value);
					this.SendPropertyChanging();
					this._giaSP = value;
					this.SendPropertyChanged("giaSP");
					this.OngiaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaKM", DbType="Int")]
		public System.Nullable<int> giaKM
		{
			get
			{
				return this._giaKM;
			}
			set
			{
				if ((this._giaKM != value))
				{
					this.OngiaKMChanging(value);
					this.SendPropertyChanging();
					this._giaKM = value;
					this.SendPropertyChanged("giaKM");
					this.OngiaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ton_kho", DbType="Int")]
		public System.Nullable<int> ton_kho
		{
			get
			{
				return this._ton_kho;
			}
			set
			{
				if ((this._ton_kho != value))
				{
					this.Onton_khoChanging(value);
					this.SendPropertyChanging();
					this._ton_kho = value;
					this.SendPropertyChanged("ton_kho");
					this.Onton_khoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_man_hinh", DbType="NVarChar(50)")]
		public string man_hinh
		{
			get
			{
				return this._man_hinh;
			}
			set
			{
				if ((this._man_hinh != value))
				{
					this.Onman_hinhChanging(value);
					this.SendPropertyChanging();
					this._man_hinh = value;
					this.SendPropertyChanged("man_hinh");
					this.Onman_hinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kich_thuoc", DbType="NVarChar(50)")]
		public string kich_thuoc
		{
			get
			{
				return this._kich_thuoc;
			}
			set
			{
				if ((this._kich_thuoc != value))
				{
					this.Onkich_thuocChanging(value);
					this.SendPropertyChanging();
					this._kich_thuoc = value;
					this.SendPropertyChanged("kich_thuoc");
					this.Onkich_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera", DbType="NVarChar(50)")]
		public string camera
		{
			get
			{
				return this._camera;
			}
			set
			{
				if ((this._camera != value))
				{
					this.OncameraChanging(value);
					this.SendPropertyChanging();
					this._camera = value;
					this.SendPropertyChanged("camera");
					this.OncameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_sac", DbType="NVarChar(50)")]
		public string cong_sac
		{
			get
			{
				return this._cong_sac;
			}
			set
			{
				if ((this._cong_sac != value))
				{
					this.Oncong_sacChanging(value);
					this.SendPropertyChanging();
					this._cong_sac = value;
					this.SendPropertyChanged("cong_sac");
					this.Oncong_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh_sp", DbType="NVarChar(50)")]
		public string anh_sp
		{
			get
			{
				return this._anh_sp;
			}
			set
			{
				if ((this._anh_sp != value))
				{
					this.Onanh_spChanging(value);
					this.SendPropertyChanging();
					this._anh_sp = value;
					this.SendPropertyChanged("anh_sp");
					this.Onanh_spChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_hot", DbType="Int")]
		public System.Nullable<int> sp_hot
		{
			get
			{
				return this._sp_hot;
			}
			set
			{
				if ((this._sp_hot != value))
				{
					this.Onsp_hotChanging(value);
					this.SendPropertyChanging();
					this._sp_hot = value;
					this.SendPropertyChanged("sp_hot");
					this.Onsp_hotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trong_luong", DbType="NVarChar(50)")]
		public string trong_luong
		{
			get
			{
				return this._trong_luong;
			}
			set
			{
				if ((this._trong_luong != value))
				{
					this.Ontrong_luongChanging(value);
					this.SendPropertyChanging();
					this._trong_luong = value;
					this.SendPropertyChanged("trong_luong");
					this.Ontrong_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mau_sac", DbType="NVarChar(50)")]
		public string mau_sac
		{
			get
			{
				return this._mau_sac;
			}
			set
			{
				if ((this._mau_sac != value))
				{
					this.Onmau_sacChanging(value);
					this.SendPropertyChanging();
					this._mau_sac = value;
					this.SendPropertyChanged("mau_sac");
					this.Onmau_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bao_hanh", DbType="NVarChar(50)")]
		public string bao_hanh
		{
			get
			{
				return this._bao_hanh;
			}
			set
			{
				if ((this._bao_hanh != value))
				{
					this.Onbao_hanhChanging(value);
					this.SendPropertyChanging();
					this._bao_hanh = value;
					this.SendPropertyChanged("bao_hanh");
					this.Onbao_hanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuat_xu", DbType="NVarChar(50)")]
		public string xuat_xu
		{
			get
			{
				return this._xuat_xu;
			}
			set
			{
				if ((this._xuat_xu != value))
				{
					this.Onxuat_xuChanging(value);
					this.SendPropertyChanging();
					this._xuat_xu = value;
					this.SendPropertyChanged("xuat_xu");
					this.Onxuat_xuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danh_muc", DbType="BigInt")]
		public System.Nullable<long> id_danh_muc
		{
			get
			{
				return this._id_danh_muc;
			}
			set
			{
				if ((this._id_danh_muc != value))
				{
					if (this._tb_danh_muc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._id_danh_muc = value;
					this.SendPropertyChanged("id_danh_muc");
					this.Onid_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienThi", DbType="Int")]
		public System.Nullable<int> hienThi
		{
			get
			{
				return this._hienThi;
			}
			set
			{
				if ((this._hienThi != value))
				{
					this.OnhienThiChanging(value);
					this.SendPropertyChanging();
					this._hienThi = value;
					this.SendPropertyChanged("hienThi");
					this.OnhienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", DbType="NVarChar(50)")]
		public string pin
		{
			get
			{
				return this._pin;
			}
			set
			{
				if ((this._pin != value))
				{
					this.OnpinChanging(value);
					this.SendPropertyChanging();
					this._pin = value;
					this.SendPropertyChanged("pin");
					this.OnpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_danh_muc_tb_sp", Storage="_tb_danh_muc", ThisKey="id_danh_muc", OtherKey="id_danh_muc", IsForeignKey=true)]
		public tb_danh_muc tb_danh_muc
		{
			get
			{
				return this._tb_danh_muc.Entity;
			}
			set
			{
				tb_danh_muc previousValue = this._tb_danh_muc.Entity;
				if (((previousValue != value) 
							|| (this._tb_danh_muc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_danh_muc.Entity = null;
						previousValue.tb_sps.Remove(this);
					}
					this._tb_danh_muc.Entity = value;
					if ((value != null))
					{
						value.tb_sps.Add(this);
						this._id_danh_muc = value.id_danh_muc;
					}
					else
					{
						this._id_danh_muc = default(Nullable<long>);
					}
					this.SendPropertyChanged("tb_danh_muc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_don_dat_hang")]
	public partial class tb_don_dat_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_don_dat_hang;
		
		private string _ten_nguoi_mua;
		
		private System.Nullable<long> _id_san_pham;
		
		private System.Nullable<int> _so_luong;
		
		private string _Dia_chi;
		
		private System.Nullable<int> _so_dien_thoai;
		
		private System.Nullable<int> _hienThi;
		
		private System.Nullable<long> _id_phu_kien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_don_dat_hangChanging(long value);
    partial void Onid_don_dat_hangChanged();
    partial void Onten_nguoi_muaChanging(string value);
    partial void Onten_nguoi_muaChanged();
    partial void Onid_san_phamChanging(System.Nullable<long> value);
    partial void Onid_san_phamChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void OnDia_chiChanging(string value);
    partial void OnDia_chiChanged();
    partial void Onso_dien_thoaiChanging(System.Nullable<int> value);
    partial void Onso_dien_thoaiChanged();
    partial void OnhienThiChanging(System.Nullable<int> value);
    partial void OnhienThiChanged();
    partial void Onid_phu_kienChanging(System.Nullable<long> value);
    partial void Onid_phu_kienChanged();
    #endregion
		
		public tb_don_dat_hang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_don_dat_hang", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_don_dat_hang
		{
			get
			{
				return this._id_don_dat_hang;
			}
			set
			{
				if ((this._id_don_dat_hang != value))
				{
					this.Onid_don_dat_hangChanging(value);
					this.SendPropertyChanging();
					this._id_don_dat_hang = value;
					this.SendPropertyChanged("id_don_dat_hang");
					this.Onid_don_dat_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nguoi_mua", DbType="NVarChar(50)")]
		public string ten_nguoi_mua
		{
			get
			{
				return this._ten_nguoi_mua;
			}
			set
			{
				if ((this._ten_nguoi_mua != value))
				{
					this.Onten_nguoi_muaChanging(value);
					this.SendPropertyChanging();
					this._ten_nguoi_mua = value;
					this.SendPropertyChanged("ten_nguoi_mua");
					this.Onten_nguoi_muaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="BigInt")]
		public System.Nullable<long> id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_chi", DbType="NVarChar(MAX)")]
		public string Dia_chi
		{
			get
			{
				return this._Dia_chi;
			}
			set
			{
				if ((this._Dia_chi != value))
				{
					this.OnDia_chiChanging(value);
					this.SendPropertyChanging();
					this._Dia_chi = value;
					this.SendPropertyChanged("Dia_chi");
					this.OnDia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="Int")]
		public System.Nullable<int> so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hienThi", DbType="Int")]
		public System.Nullable<int> hienThi
		{
			get
			{
				return this._hienThi;
			}
			set
			{
				if ((this._hienThi != value))
				{
					this.OnhienThiChanging(value);
					this.SendPropertyChanging();
					this._hienThi = value;
					this.SendPropertyChanged("hienThi");
					this.OnhienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phu_kien", DbType="BigInt")]
		public System.Nullable<long> id_phu_kien
		{
			get
			{
				return this._id_phu_kien;
			}
			set
			{
				if ((this._id_phu_kien != value))
				{
					this.Onid_phu_kienChanging(value);
					this.SendPropertyChanging();
					this._id_phu_kien = value;
					this.SendPropertyChanged("id_phu_kien");
					this.Onid_phu_kienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
